name: ON | PUSH | MAIN
run-name: CREATE RELEASE | MAIN

# When pushing to main, run the following jobs:
# - Call the release-manager to create a release

on:
  push:
    branches:
      - main

jobs:
  release-manager:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/release-manager.yaml
    with:
      version-file: package.json
      version-path: version
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.USP_GITHUB_ADMIN_FINE_GRAINED_ACCES_TOKEN }}
